# Generated by Django 6.0.4 on 2026-04-28 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('presidente', models.CharField(max_length=100)),
                ('escudo', models.CharField(max_length=250)),
                ('estadio', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Mediocampo'), ('DEL', 'Delantero')], max_length=100)),
                ('equipo_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga_Corrupta_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_movimiento', models.CharField(choices=[('FICH', 'Fichaje'), ('CES', 'Cesión'), ('RET', 'Retirado')], max_length=100)),
                ('equipo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_destino', to='Liga_Corrupta_app.equipo')),
                ('equipo_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_origen', to='Liga_Corrupta_app.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga_Corrupta_app.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='Liga_Corrupta_app.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='Liga_Corrupta_app.equipo')),
                ('goles_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga_Corrupta_app.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga_Corrupta_app.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('GOL', 'Gol'), ('ASI', 'Asitencia'), ('TAM', 'Tarjeta Amarilla'), ('TAR', 'Tarjeta Roja'), ('LES', 'Lesión'), ('GOP', 'Gol Propia'), ('PEF', 'Penalti Fallado'), ('PEC', 'Penalti cometido')], max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga_Corrupta_app.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga_Corrupta_app.partido')),
            ],
        ),
    ]
