# Generated by Django 6.0.4 on 2026-04-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga_Corrupta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='entrenador',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
